[[broker]]
name = "bostonmesh"
enabled = true
server = "mqttmc01.bostonme.sh"
port = 443
transport = "websockets"
keepalive = 55
qos = 0
retain = true

[broker.tls]
enabled = true
verify = true

[broker.auth]
method = "token"
audience = "mqttmc01.bostonme.sh"
