[[broker]]
name = "cascadiamesh"
enabled = true
server = "mqtt-v1.cascadiamesh.org"
port = 443
transport = "websockets"
keepalive = 55
qos = 0
retain = true

[broker.tls]
enabled = true
verify = true

[broker.auth]
method = "token"
audience = "mqtt-v1.cascadiamesh.org"
