[[broker]]
name = "coloradomesh"
enabled = true
server = "mqtt.meshcore.coloradomesh.org"
port = 1883
transport = "websockets"
keepalive = 55
qos = 0
retain = true

[broker.tls]
enabled = true
verify = true

[broker.auth]
method = "token"
audience = "mqtt.meshcore.coloradomesh.org"
