[[broker]]
name = "meshcore-ca-1"
enabled = true
server = "mqtt1.meshcore.ca"
port = 443
transport = "websockets"
keepalive = 55
qos = 0
retain = true

[broker.tls]
enabled = true
verify = true

[broker.auth]
method = "token"
audience = "mqtt1.meshcore.ca"

[[broker]]
name = "meshcore-ca-2"
enabled = true
server = "mqtt2.meshcore.ca"
port = 443
transport = "websockets"
keepalive = 55
qos = 0
retain = true

[broker.tls]
enabled = true
verify = true

[broker.auth]
method = "token"
audience = "mqtt2.meshcore.ca"
