[[broker]]
name = "meshat.se"
enabled = true
server = "mqtt.meshat.se"
port = 8883
transport = "tcp"
keepalive = 55
qos = 0
retain = true

[broker.tls]
enabled = true
verify = true

[broker.auth]
method = "password"
username = "msh"
password = "msh"
