[[broker]]
name = "ntxmesh"
enabled = true
server = "ntxmesh.dhovin.me"
port = 443
transport = "websockets"
keepalive = 55
qos = 0
retain = true

[broker.tls]
enabled = true
verify = true

[broker.auth]
method = "token"
audience = "ntxmesh.dhovin.me"
