[[broker]]
name = "nz-analyzer"
enabled = true
server = "meshcore-mqtt-1.baird.io"
port = 443
transport = "websockets"
keepalive = 55
qos = 0
retain = true

[broker.tls]
enabled = true
verify = true

[broker.auth]
method = "token"
audience = "meshcore-mqtt-1.baird.io"
