[[broker]]
name = "waev"
enabled = true
server = "mqtt.waev.app"
port = 443
transport = "websockets"
keepalive = 55
qos = 0
retain = false

[broker.tls]
enabled = true
verify = true

[broker.auth]
method = "token"
audience = "mqtt.waev.app"
